Directory:
  exp_name: 241113_newsample_V2
  data_dir: ./vio/data/
  log_dir: ./tensorboard
  weights: ./weights
  results: ./results

Train:
  use_shuffle: True
  train_log_interval: 10
  valid_log_interval: 10
  img_w: 256
  img_h: 256
  v_f_len: 512
  i_f_len: 256
  imu_dropout: 0.2
  rnn_hidden_size: 512 #1024
  rnn_dropout: 0.2 #0.2
  weight_decay: 0.00001
  batch_size: 8 # 1
  seq_len: 11
  epoch: 101
  epochs_warmup: 30
  epochs_joint: 80
  init_lr: 0.001
  lr_warmup: 0.0005 # 0.0005
  lr_joint: 0.00005 # 0.00005
  lr_fine: 0.000001 # 0.000001
  eta: 0.05
  temp_init: 5
  Lamda: 0.00003