Directory:
  exp_name: 241113_newsample_V2
  data_dir: ./vio/data/
  log_dir: ./tensorboard
  weights: ./weights
  results: ./results

Train:
  use_shuffle: True
  train_log_interval: 10
  valid_log_interval: 10
  train_plot_interval: 100
  valid_plot_interval: 100
  img_w: 1280
  img_h: 720
  weight_decay: 0.00001
  batch_size: 8 # 1
  epoch: 101
  init_lr: 0.0001