Directory:
  exp_name: resnet_mixedPrecision_Step=2
  data_dir: ./vio/data/
  log_dir: ./tensorboard
  weights: ./weights
  results: ./results

Dataset:
  tspxr_capture: False
  mars_logger: True

Train:
  use_shuffle: True
  train_log_interval: 10
  valid_log_interval: 10
  train_plot_interval: 100 # 100
  valid_plot_interval: 100
  img_w: 640
  img_h: 480
  weight_decay: 0.0001
  beta1: 0.9
  batch_size: 8 # 1
  epoch: 101
  init_lr: 0.0001

Experiment:
  gpus: [1] # [0, 1]
  gpu_vram: 24000
  gpu_vram_factor: 0.8