Directory:
  exp_name: test_tf2.12_gradient_tape
  data_dir: ./vio/data/
  log_dir: ./tensorboard
  weights: ./weights
  results: ./results

Dataset:
  custom_data: False
  mars_logger: True

Train:
  use_shuffle: True
  train_plot_interval: 200 # 100
  valid_plot_interval: 50
  vis_batch_size: 1
  num_source: 2
  num_scale: 4
  imu_seq_len: 10
  min_depth: 0.1
  max_depth: 10.0
  ssim_ratio: 0.85
  smoothness_ratio: 0.001
  auto_mask: True
  img_w: 640
  img_h: 480
  weight_decay: 0.0001
  beta1: 0.9
  batch_size: 8 # 1
  epoch: 101
  init_lr: 0.0001
  end_lr: 0.00001

Experiment:
  gpus: [0] # [0, 1]
  gpu_vram: 24000
  gpu_vram_factor: 0.8